### PR TITLE
fix: do not use RepositoryUrl from GitInfo

### LINKED ISSUE #281: The bot no longer responds to the user if command execution fails
### Description

image

### Expected vs. Actual Behavior

The expected behavior is that the bot responds to the user notifying them that an error occurred

The actual behavior is that the bot gets stuck with `is thinking` status

### Reproduction Steps

1. Try to run a command that returns an error

### Other Information

Suspects:
#275 (merged 3 hours ago as of writing)
#268 (merged yesterday as of writing)

### PR DESCRIPTION
**Pull request by Octol1ttle**
GitInfo's `RepositoryUrl` string depends on origin URL, which is unvalidated user input that isn't even guaranteed to exist. This can cause [issues that are almost impossible to debug](https://github.com/TeamOctolings/Octobot/issues/281)

Closes #281

### CODE REVIEW

File: src/BuildInfo.cs [hunk 1]
```diff
@@ -2,15 +2,15 @@
 
 public static class BuildInfo
 {
-    public static string RepositoryUrl => ThisAssembly.Git.RepositoryUrl;
+    public const string RepositoryUrl = "https://github.com/TeamOctolings/Octobot";
```
Comment (mctaylors) [inline src/BuildInfo.cs:5]: do you mind if I try to get the repository and its author automatically?

Comment (Octol1ttle) [reply src/BuildInfo.cs:5]: how would you do that..?

Comment (mctaylors) [reply src/BuildInfo.cs:5]:
```regex
[a-z0-9].*\.[a-z0-9]+[\/|:]([a-z0-9]+)\/([a-z0-9]+)
```

Comment (Octol1ttle) [reply src/BuildInfo.cs:5]: again, we can't rely on unvalidated user input. what if there is no remote set? what if the remote URL is complete nonsense?

best to just drop it instead of trying to hack around every possible edge case

**Review by mctaylors — APPROVED** [review]
